# Generated by Django 5.1.5 on 2025-02-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternatePrice',
            field=models.FloatField(default=0),
        ),
    ]
